file_format: "1"
id: lebeda
name: LeBeDa
type: shield
url: https://github.com/MatusFrick/LeBeDa
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - lebeda_left
  - lebeda_right
